// Copyright 2026 Shuaib Rao
// SPDX-License-Identifier: Apache-2.0
package com.googlecode.cqengine.persistence.disk;

import com.googlecode.cqengine.ConcurrentIndexedCollection;
import com.googlecode.cqengine.IndexedCollection;
import com.googlecode.cqengine.attribute.SimpleAttribute;
import com.googlecode.cqengine.testutil.TestAssertions;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.Properties;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.atomic.AtomicInteger;

import static com.googlecode.cqengine.query.QueryFactory.simpleAttribute;
import static java.util.concurrent.TimeUnit.SECONDS;

/**
 * Unit tests for the {@code shared_cache} mode of {@link DiskPersistence}.
 */
public class DiskSharedCacheConcurrencyTest {

    /**
     * Unit test which demonstrates the value of using a read-write lock when {@code shared_cache} mode is enabled.
     * <p>
     * This fails if {@code shared_cache} is enabled while {@code use_read_write_lock} is disabled,
     * and it passes when {@code shared_cache} is enabled and {@code use_read_write_lock} is also enabled.
     */
    @Test
    public void testDiskSharedCacheConcurrency() throws InterruptedException {
        Properties properties = new Properties();
        properties.setProperty("shared_cache", "true");
        properties.setProperty("use_read_write_lock", "true");

        final int NUM_BACKGROUND_THREADS = 4;

        // Integer generator...
        final AtomicInteger idCounter = new AtomicInteger(0);

        // A POJO class, where every instance has a different id generated by the integer generator above...
        class TestPojo {
            Integer id = idCounter.incrementAndGet();
        }

        // An attribute which reads the id field of the POJO...
        final SimpleAttribute<TestPojo, Integer> primaryKey =
                simpleAttribute(TestPojo.class, Integer.class, "id", object -> object.id);

        // Create a temp file...
        File tempFile = DiskPersistence.createTempFile();

        // Create a collection of TestPojo objects which persists to the temp file...
        DiskPersistence<TestPojo, Integer> persistence =
                DiskPersistence.onPrimaryKeyInFileWithProperties(primaryKey, tempFile, properties);
        try {
            IndexedCollection<TestPojo> collection = new ConcurrentIndexedCollection<>(persistence);

            // Prepare a latch which will tell us when all background threads have finished executing...
            final CountDownLatch latch = new CountDownLatch(NUM_BACKGROUND_THREADS);

            // Start the background threads...
            for (int i = 0; i < NUM_BACKGROUND_THREADS; i++) {
                new Thread(() -> {
                    // In each background thread, add one new object to the collection...
                    try {
                        collection.add(new TestPojo());
                    }
                    catch (Exception ignore) { }
                    finally {
                        latch.countDown();
                    }
                }).start();
            }
            // Wait for all background threads to finish...
            latch.await(20, SECONDS);

            // Assert that the same number of objects were inserted as there were background threads...
            TestAssertions.assertEquals(NUM_BACKGROUND_THREADS, collection.size());
        }
        finally {
            // Windows refuses to delete a file while the persistence still holds it open.
            persistence.close();
        }

        // Delete the temp file...
        TestAssertions.assertEquals(true, tempFile.delete());
    }
}
